### ISSUE TITLE
Add  Center Heading "CSI Events" 

### ISSUE THREAD

**Issue by darshikapongallu** [CSI-CATT-DMCE/csi-website-hacktoberfest2021#4]
Page to be used ```events.html```
### Below heading add a nav-bar in center and buttons should be in center & on-click they should be active.
![events navbar](https://user-images.githubusercontent.com/71728477/138228438-e89055a9-ecb9-4197-b643-09a85af59dea.PNG)

**Comment by yash-png** [comment]
I can center heading

**Comment by Karan2310** [comment]
Go Ahead


> I can center heading

Go Ahead

**Comment by Karan2310** [comment]
> I can center heading
Go Ahead!
